### ISSUE TITLE
Use probeFamily instead of probeType

### ISSUE THREAD

**Issue by danielo515** [madoos/config-probes-microservice#11]
En mi opinión family es un término mucho más apropiado y semántico que type. Type es usado para tipos de datos y un montón de cosas más que pueden llevarnos a confusión. Mientras que family es un concepto claro y conciso, grupo de cosas que comparten características comunes.

Es mi opinión, dadme la vuestra

**Comment by danielo515** [comment]
@vrublevskyy @victorgtp

**Comment by vrublevskyy** [comment]
@danielo515 Me parece bien, lo actualizo en la rama feature/FixJoiModel

**Comment by danielo515** [comment]
Gracias señor... Aunque muchas issues para tan poca rama...
