### ISSUE TITLE
Valid probeTypes are agent and picoprobe

### ISSUE THREAD

**Issue by danielo515** [madoos/config-probes-microservice#4]
@vrublevskyy 
Los probeTypes válidos deberían ser `picoprobe` y `agent`, pero en su lugar veo dos cosas muy distintas:

https://github.com/madoos/config-probes-microservice/blob/develop/model/joi/testBattery.js#L16

Me adelanto a tu comentario y si nos limitamos a quedarnos con lo que ya existe vamos listos a la hora de crear un microservicio.

@Miguel-Herrero

**Comment by vrublevskyy** [comment]
@danielo515 cambio picosonda y app por picoprobe y agent

**Comment by danielo515** [comment]
Dónde lo cambias?
Pull request? Commit? Por favor, usad referencias desde los commits y los PRs, si no esto se vuelve un caos

**Comment by vrublevskyy** [comment]
@danielo515 esta en la branch:
https://github.com/madoos/config-probes-microservice/tree/feature/FixJoiModel
