### ISSUE TITLE
Reorganize folder structure to separate src from the rest 

### ISSUE THREAD

**Issue by danielo515** [madoos/config-probes-microservice#5]
Normalmente el código fuente está contenido bajo un único directorio en la raíz (con su directorios obviamente) y el resto (como los test, o los scripts) en otras carpetas a la misma altura. 

La organización que propongo es :

- root
  -  src 
  -  bin
  -  mongo 
  -  package.json etc

**Comment by madoos** [comment]
Perfecto, ya lo tienes en el repo!!

**Comment by danielo515** [comment]
Gracias @madoos ,

El root era solo una alegoría del directorio raíz, no me refería a añadirlo literalmente. Meto lo que hay en root en src.

Un saludo

**Comment by danielo515** [comment]
Por lo que veo lo has hecho directamente en develop.
Para la próxima podrías hacer una rama y un PR?
